safe: false
permalink: pretty
google-analytics-id: "UA-63717309-1"

assets:
    js_compressor: yui

gems:
- jekyll-assets
- jekyll-sitemap
- jekyll_version_plugin

collections:
  concepts:
    output: true
    permalink: /:title/

  proofs:
    output: true
    permalink: /:path/

defaults:
    -
        scope:
            path: ""
            type: "concepts"
        values:
            layout: concept
            type: concept
            tags: [untagged]
    -
        scope:
            path: ""
            type: "proofs"
        values:
            layout: proof
            type: proof
            tags: [untagged]
            sourcefiles: source/PlayState.hx



exclude: [vendor, .gitignore, Gemfile, Gemfile.lock, README.md, Rakefile, credentials.yaml, .travis.yml, build, key, key.enc]

tag_page_layout: tag_page
tag_page_dir: tags

tags: [haxeflixel, flixel, haxe]
